import Head from "next/head";
import PodcastList from "../components/PodcastList";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full bg-bg flex flex-col md:flex-row items-start md:gap-x-4 ">
        <Sidebar />
        <div className="w-full overflow-y-auto h-full md:ml-10 p-4">
          <PodcastList title="Technology" />
          <PodcastList title="Comedy" />
          <PodcastList title="Education" />
          <PodcastList title="Learning" />
        </div>
      </main>
    </div>
  );
}
